=== DelphiMarkus/CaveYard/xml-resources/jaxb/XMLMap/mapSchema.xsd
<?xml version="1.0"?>

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns="caveyard.map"
           targetNamespace="caveyard.map"
           elementFormDefault="qualified">

    <xs:element name="map" type="mapType" />

    <xs:complexType name="mapType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="cells" type="cellsType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cellsType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element name="cell" type="cellType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="cellType">
        <xs:all>
            <xs:element name="file" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="node" type="xs:string" default="" minOccurs="0" maxOccurs="1"/>
            <xs:element name="offset" nillable="true" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:attribute name="x" type="xs:float" default="0"/>
                    <xs:attribute name="y" type="xs:float" default="0"/>
                    <xs:attribute name="z" type="xs:float" default="0"/>
                </xs:complexType>
            </xs:element>
        </xs:all>

        <xs:attribute name="x" type="xs:float" use="required"/>
        <xs:attribute name="y" type="xs:float" default="0" use="optional"/>
        <xs:attribute name="z" type="xs:float" use="required"/>
        <xs:attribute name="size_x" type="xs:float" use="required"/>
        <xs:attribute name="size_z" type="xs:float" use="required"/>
    </xs:complexType>
</xs:schema>

=== DelphiMarkus/CaveYard/assets/Data/map/test.map.xml
<?xml version="1.0" encoding="UTF-8"?>

<map xmlns="caveyard.map"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:schemaLocation="caveyard.map
                         ../schemas/mapSchema.xsd">

    <cells>
        <cell x="0" z="0" size_x="40" size_z="40">
            <file>Models/landscape_test2/landscape_test2_copy.j3o</file>
            <offset x="-20" z="-20"/>
        </cell>
        <cell x="0" z="-40" size_x="40" size_z="40">
            <file>Models/landscape_test2/landscape_test2_copy.j3o</file>
            <offset x="-20" z="-20"/>
        </cell>
        <cell x="-40" z="0" size_x="40" size_z="40">
            <file>Models/landscape_test2/landscape_test2_copy.j3o</file>
            <offset x="-20" z="-20"/>
        </cell>
        <cell x="-40" z="-40" size_x="40" size_z="40">
            <file>Models/landscape_test2/landscape_test2_copy.j3o</file>
            <offset x="-20" z="-20"/>
        </cell>
        <cell x="1" z="3" size_x="2" size_z="1">
            <file>Models/misc/TÃ¼r.j3o</file>
            <offset x="-3"/>
        </cell>
    </cells>
</map>
